openapi: 3.0.0
info:
  title: MiniReipaz API
  version: 1.0.0
servers:
  - url: http://localhost:3010
    description: Local frontend server
paths:
  /api/ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /api/users/{name}:
    get:
      summary: Get user by name
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /{path}:
    get:
      summary: Error route for undefined paths
      parameters:
        - in: path
          name: path
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string